Improve rosjava compatibility with Mac OS X
git-svn-id: file:///home/dthomas/wg/migration/svn2git/ros-svn/stacks/ros_experimental/trunk@7214 61973afe-1cd6-434e-a0a9-934cb0052259

diff --git a/rosjava/scripts/rosjava_gen_exe b/rosjava/scripts/rosjava_gen_exe
--- a/rosjava/scripts/rosjava_gen_exe
+++ b/rosjava/scripts/rosjava_gen_exe
@@ -11,13 +11,21 @@ ROSJAVA_BASE_DIR=$(rospack find rosjava)
 cat <<EOF > $3
 #!/bin/bash
 
-LIBJSIG=\`find \$JAVA_HOME/jre/lib/ -maxdepth 2 -name "libjsig.so"\`
-if [ -z "\$LIBJSIG" ]; then
-  echo "Cannot find libjsig ... maybe you need to set JAVA_HOME?"
-  exit 1
+OS=\`uname -s\`
+if [ "\$OS" == "Darwin" ] ; then
+  DYLD_LIBRARY_PATH=${ROSJAVA_BASE_DIR}/bin java -classpath $1 $2 ${@:4}
+else
+  LIBJSIG=\`find \$JAVA_HOME/jre/lib/ -maxdepth 2 -name "libjsig.so"\`
+  if [ -z "\$LIBJSIG" ]; then
+    echo "Cannot find libjsig ... maybe you need to set JAVA_HOME?"
+    exit 1
+  fi
+
+  LD_PRELOAD=\$LIBJSIG LD_LIBRARY_PATH=${ROSJAVA_BASE_DIR}/bin java -classpath $1 $2 ${@:4}
 fi
 
-LD_PRELOAD=\$LIBJSIG LD_LIBRARY_PATH=${ROSJAVA_BASE_DIR}/bin java -classpath $1 $2 ${@:4}
+
 EOF
 
 chmod 755 $3
+
