allow relative path for second arg to rosrun, #3641

diff --git a/tools/rosbash/scripts/rosrun b/tools/rosbash/scripts/rosrun
--- a/tools/rosbash/scripts/rosrun
+++ b/tools/rosbash/scripts/rosrun
@@ -13,6 +13,14 @@ if [ $# -lt 2 ]; then
   echo "  If it finds it, it will run it with ARGS."
   exit 1
 fi
+# early check that filename does not end with '/' 
+case $2 in 
+		*/) echo "Invalid filename: " $2	
+				exit 1 
+				;; 
+esac 
+# basename also makes .//foo into foo 
+basename=`basename $2`
 if [[ -n $CATKIN_SOURCE_DIR ]]; then
     catkin_source_dir=`ROS_ROOT=$CATKIN_SOURCE_DIR ROS_PACKAGE_PATH= rospack find $1`
 fi 
@@ -26,11 +34,12 @@ pkgdir=`rospack find $1`
 if [[ -z $catkin_source_dir && -z $catkin_binary_dir && -z $pkgdir ]]; then
     return 2
 fi
-# The -perm /mode usage is not available in find on the Mac
-#exepathlist=(`find $pkgdir -name $2 -type f -perm /u+x,g+x,o+x`)
-# -L: #3475
-exepathlist=(`find -L $catkin_source_dir $catkin_binary_dir $pkgdir -name $2 -type f  -perm +111 ! -regex ".*$pkgdir\/build\/.*" | uniq`)
-if [[ ${#exepathlist[@]} == 0 ]] ; then
+if [[ ! $2 == */* ]]; then 
+  # The -perm /mode usage is not available in find on the Mac
+  #exepathlist=(`find $pkgdir -name $2 -type f -perm /u+x,g+x,o+x`)
+  # -L: #3475
+  exepathlist=(`find -L $catkin_source_dir $catkin_binary_dir $pkgdir -name $2 -type f  -perm +111 ! -regex ".*$pkgdir\/build\/.*" | uniq`)
+  if [[ ${#exepathlist[@]} == 0 ]] ; then
     echo "[rosrun] Couldn't find executable named $2 below $pkgdir"
     nonexepathlist=(`find -H $pkgdir -name $2`)
     if [[ ${#nonexepathlist[@]} != 0 ]] ; then
@@ -41,14 +50,23 @@ if [[ ${#exepathlist[@]} == 0 ]] ; then
       done
     fi
     exit 3
-elif [[ ${#exepathlist[@]} -gt 1 ]] ; then
+
+  elif [[ ${#exepathlist[@]} -gt 1 ]] ; then
     echo "[rosrun] You have chosen a non-unique executable, please pick one of the following:"
     select opt in ${exepathlist[@]}; do
         exepath=$opt
         break
     done
+  else 
+		exepath=${exepathlist[0]} 
+	fi 
 else
-    exepath=${exepathlist[0]}
+	absname=$pkgdir/$2 
+	if [ ! -f $absname -o ! -x $absname ] ; then 
+		echo "[rosrun] Couldn't find executable named $absname" 
+		exit 3 
+	fi 
+	exepath=$absname 
 fi
 shift
 shift
